#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have /bin/bash, /bin/ksh, or similar, try running
#       the script with one of these shells: bash, ksh or sh
#   (2) The Java home directory must be set to a Java SDK directory
#       (not a JRE directory) and included in your PATH
#
#   Gradle will print a welcome message when it is run from console.
#
#   Gradle "wrapper" resolution of dependencies.
#   "Single entry point version" as mentioned in
#   https://github.com/gradle/gradle/issues/2537
#
#   Simplify customization of startup script in the Gradle project by
#   replacing default wrapper script with an alternative template that
#   can be customized as needed.
#
#   However, if you modify this script, it could break the Gradle wrapper
#   mechanism for other users on the same project, so use the wrapper
#   during development, rather than changing to match the local setup.
#
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_NAME="gradlew"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn ( ) {
    echo "$*" >&2
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

PROG="$0"
WRAPPER_SCRIPT_DIR=`cd "$(dirname "$PROG")" >/dev/null && pwd`
WRAPPER_SCRIPT_NAME=`basename "$PROG"`
WRAPPER_JAR="$WRAPPER_SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar"
WRAPPER_PROPERTIES="$WRAPPER_SCRIPT_DIR/gradle/wrapper/gradle-wrapper.properties"
BOOTSTRAP_CLASSPATH_OVERRIDE="${WRAPPER_BOOTSTRAP_CLASSPATH_OVERRIDE:-}"

# Determine if bash or sh should be used
if [ "$NONSTOP" = "true" ] ; then
    sh_runner="sh"
else
    if [ -z "$SHELL" ]; then
        sh_runner="sh"
    else
        sh_runner="$SHELL"
    fi
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

if [ -z "$JAVA_HOME" ] ; then
    warn "JAVA_HOME environment variable is not set"
fi

# For Cygwin or MSYS issue warning about paths
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path -m "$APP_HOME"`
    CP="`cygpath -wp "$CLASSPATH"`"
    CLASSPATH="$CP"
    WRAPPER_JAR=`cygpath --path -m "$WRAPPER_JAR"`
    WRAPPER_PROPERTIES=`cygpath --path -m "$WRAPPER_PROPERTIES"`
fi

# Escape application home for MinGW bash on Windows.
if [ "$OSTYPE" = "msys" ] ; then
    APP_HOME="`(cd "$APP_HOME" && pwd -W)`"
fi

APP_HOME_PARENT="$(dirname "$APP_HOME")"
BOOTSTRAP_CLASSPATH="$WRAPPER_JAR"

# Determine the main class
MAIN_CLASS="org.gradle.wrapper.GradleWrapperMain"

# Usually the classpath is not needed, but in some edge cases the user
# may have customized gradle.properties and the Gradle wrapper should
# be bootstrapped with a custom classpath.
if [ ! -z "$BOOTSTRAP_CLASSPATH_OVERRIDE" ] ; then
    CLASSPATH="$BOOTSTRAP_CLASSPATH_OVERRIDE"
else
    CLASSPATH="$BOOTSTRAP_CLASSPATH"
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add -Xdock options
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS convert paths
if [ "$cygwin" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CP="`cygpath --path --mixed "$CLASSPATH"`"
    CLASSPATH="$CP"
    WRAPPER_JAR=`cygpath --path --mixed "$WRAPPER_JAR"`
    WRAPPER_PROPERTIES=`cygpath --path --mixed "$WRAPPER_PROPERTIES"`
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#   * shell commands, such as variables, or quoted strings,
#   * so we must use eval to properly construct the java command line
#   * We use double quotes to make variable expansion work,
#   * but we have to quote every single variable or expression
#   * to make sure the shell treats them as atomic units.
#
# Splitting the LINE into an array ARGS is the best way to handle
# the command line in Bash. Split the command line at a space so we
# can handle paths that contain spaces.
set -- "$WRAPPER_JAR" "$WRAPPER_PROPERTIES" "$@"

exec "$JAVACMD" "${DEFAULT_JVM_OPTS[@]}" $GRADLE_OPTS -classpath "$CLASSPATH" $MAIN_CLASS "$@"
